name: Publish library
permissions: write-all

on:
  push:
    tags:
      - v*

jobs:
  publish-lib:
    name: Publish library
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-publish-lib
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          cache: npm
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@agusmgarcia"

      - name: Install dependencies
        run: npm ci --ignore-scripts
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: get-version-from-tag
        uses: frabert/replace-string-action@v2.4
        with:
          pattern: v(.*)
          string: ${{ github.ref_name }}
          replace-with: $1

      - name: Extract version from package
        id: extract-version-from-package
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .version package.json -r

      - name: Verify version match
        if: ${{ steps.get-version-from-tag.outputs.replaced != steps.extract-version-from-package.outputs.value }}
        run: |
          echo "::error::Version in the package.json and tag don't match"
          exit 1
        shell: bash

      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: Version ${{ steps.get-version-from-tag.outputs.replaced }}
          tag: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
